# appveyor.yml
version: '{build}'
image: 'Visual Studio 2017'

# Define environment variables if needed
environment:
  NANT_HOME: 'C:\NAnt'
  NANT_VERSION: '0.85'

# Install NAnt
before_build:
  - ps: |
      Write-Output "Installing NAnt..."
      Write-Output "Pulling from http://downloads.sourceforge.net/project/nant/nant/$env:NANT_VERSION/nant-$env:NANT_VERSION-bin.zip"
      Invoke-WebRequest -UserAgent "Wget" -Uri "http://downloads.sourceforge.net/project/nant/nant/$env:NANT_VERSION/nant-$env:NANT_VERSION-bin.zip" -OutFile "nant.zip"
      Write-Output "Installing to $env:NANT_HOME"
      Expand-Archive -Path "nant.zip" -DestinationPath $env:NANT_HOME
      Remove-Item "nant.zip"

# Build using NAnt
build_script:
  - ps: |
      $env:Path += ';$env:NANT_HOME\nant-$env:NANT_VERSION\bin'
      .\build.cmd package 2.0.0-sp1

# Artifacts to store after build (e.g., binaries, logs)
artifacts:
  - path: /path/to/output_directory/*
    name: Build_Artifacts
