# appveyor.yml
version: '{build}'
image: 'Visual Studio 2015'

# Define environment variables if needed
environment:
  NANT_HOME: 'C:\NAnt'
  NANT_VERSION: '0.85'

# Install NAnt
before_build:
  - ps: |
      Write-Output "Installing NAnt..."
      curl.exe -L -o nant.zip -A Wget "http://downloads.sourceforge.net/project/nant/nant/%NANT_VERSION%/nant-%NANT_VERSION%-bin.zip"
      7z.exe x "nant.zip" -o %NANT_HOME%
      Remove-Item "nant.zip"

# Build using NAnt
build_script:
  - ps: |
      set PATH=%PATH%:%NANT_HOME%\nant-%NANT_VERSION%\bin
      .\build.cmd package 2.0.0-sp1

# Artifacts to store after build (e.g., binaries, logs)
artifacts:
  - path: /path/to/output_directory/*
    name: Build_Artifacts
